# Reusable vars
x-var:
  - &POSTGRES_USER
    ${POSTGRES_USER}
  - &POSTGRES_PASSWORD
    ${POSTGRES_PASSWORD}
  - &POSTGRES_DATABASE
    ${POSTGRES_DATABASE}
  - &POSTGRES_PORT
    ${POSTGRES_PORT}
  - &POSTGRES_HOST
    ${POSTGRES_HOST}
  - &BACKEND_PORT
    ${BACKEND_PORT}
  - &S3_ENDPOINT
    ${S3_ENDPOINT}
  - &S3_ACCESS_KEY
    ${S3_ACCESS_KEY}
  - &S3_SECRET_KEY
    ${S3_SECRET_KEY}
  - &S3_BUCKET_NAME
    ${S3_BUCKET_NAME}

x-postgres-vars: &postgres-vars
  POSTGRES_HOST: *POSTGRES_HOST
  POSTGRES_USER: *POSTGRES_USER
  POSTGRES_PASSWORD: *POSTGRES_PASSWORD
  POSTGRES_DATABASE: *POSTGRES_DATABASE
  POSTGRES_PORT: *POSTGRES_PORT

x-backend-vars: &backend-vars
  BACKEND_PORT: *BACKEND_PORT
  POSTGRES_HOST: *POSTGRES_HOST
  POSTGRES_USER: *POSTGRES_USER
  POSTGRES_PASSWORD: *POSTGRES_PASSWORD
  POSTGRES_DATABASE: *POSTGRES_DATABASE
  POSTGRES_PORT: *POSTGRES_PORT
  S3_ENDPOINT: *S3_ENDPOINT
  S3_ACCESS_KEY: *S3_ACCESS_KEY
  S3_SECRET_KEY: *S3_SECRET_KEY
  S3_BUCKET_NAME: *S3_BUCKET_NAME


services:
  backend:
    build:
      context: ./backend/api
    container_name: fastapi-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db-service
    env_file:
      - .env
    volumes:
      - ./backend/api:/app
    command: uv run python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: docker.io/postgis/postgis:latest
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
