# Reusable vars
x-var:
  - &BACKEND_PORT
    ${BACKEND_PORT}
  - &S3_ENDPOINT
    ${S3_ENDPOINT}
  - &S3_ACCESS_KEY
    ${S3_ACCESS_KEY}
  - &S3_SECRET_KEY
    ${S3_SECRET_KEY}
  - &S3_BUCKET_NAME
    ${S3_BUCKET_NAME}
  - &PARQUET_PATH
    ${PARQUET_PATH}

x-backend-vars: &backend-vars
  BACKEND_PORT: *BACKEND_PORT
  S3_ENDPOINT: *S3_ENDPOINT
  S3_ACCESS_KEY: *S3_ACCESS_KEY
  S3_SECRET_KEY: *S3_SECRET_KEY
  S3_BUCKET_NAME: *S3_BUCKET_NAME
  PARQUET_PATH: *PARQUET_PATH

services:
  frontend:
    image: burn-sev-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-bs
    ports:
      - "8080:8080"

  fastapi-backend:
    image: burn-sev-backend:latest
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      <<: *backend-vars
    env_file:
      - .env
    volumes:
      - backend-data:/app/data
    command: uv run python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"

  analysis-backend:
    image: analysis-backend:latest
    build:
      context: ./analysis
      dockerfile: Dockerfile
    container_name: analysis-backend
    ports:
      - "5000:5000"
    environment:
      <<: *backend-vars
    env_file:
      - .env
    volumes:
      - analysis-data:/app/data
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
       

volumes:
  backend-data:
  analysis-data:
