{{- if and .Values.analysis.pdb  .Values.analysis.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "analysis.fullname" . }}
  labels:
    {{- include "analysis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "analysis.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.analysis.pdb.minAvailable }}
{{- end }}