{{- if .Values.analysis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "analysis.fullname" . }}
  labels:
    {{- include "analysis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.ports.analysis }}
      targetPort: {{ .Values.global.ports.analysis }}
      protocol: TCP
      name: http
  selector:
    {{- include "analysis.selectorLabels" . | nindent 4 }}
{{- end }}