# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#-- global variables, can be accessed by sub-charts.
global:
  #-- the registry where the images are stored. override during runtime for other registry at global level or individual level.
  repository: ~ # provide the repo name from where images will be sourced for example bcgo
  #-- the registry where the images are stored. override during runtime for other registry at global level or individual level. default is ghcr.io
  registry: ghcr.io # ghcr.io for directly streaming from github container registry or "artifacts.developer.gov.bc.ca/github-docker-remote" for artifactory, or any other registry.
  #-- the tag of the image, it can be latest, 1.0.0 etc..., or the sha256 hash
  tag: ~
  #-- turn off autoscaling for the entire suite by setting this to false. default is true.
  autoscaling: false
  #-- global secrets, can be accessed by sub-charts.
  secrets:
    enabled: true
    databasePassword: ~
    databaseName: ~
    persist: true
  config:
    databaseUser: ~
  #-- domain of the application, it is required, apps.silver.devops.gov.bc.ca for silver cluster and apps.devops.gov.bc.ca for gold cluster
  domain: "apps.silver.devops.gov.bc.ca" # it is apps.gold.devops.gov.bc.ca for gold cluster

  security: 
    allowInsecureImages: true

backend:
  #-- enable or disable backend
  enabled: true
  #-- the deployment strategy, can be "Recreate" or "RollingUpdate"
  deploymentStrategy: Recreate
  #-- autoscaling for the component. it is optional and is an object.
  image:
    registry: ghcr.io
    repository: bcgov/burn-severity-map/backend/api
    tag: latest # Or a specific tag
    pullPolicy: Always
  autoscaling:
    #-- enable or disable autoscaling.
    enabled: true
    #-- the minimum number of replicas.
    minReplicas: 3
    #-- the maximum number of replicas.
    maxReplicas: 7
    #-- the target cpu utilization percentage, is from request cpu and NOT LIMIT CPU.
    targetCPUUtilizationPercentage: 80
  configMap:
    enabled: false
  env:
    - name: PARQUET_PATH
      value: "burn-severity/bs.parquet"
    - name: TEMPDIR
      value: "/tmp"
    # Backend API
    - name: BACKEND_PORT
      value: 8000
    - name: FRONTEND_PORT
      value: 8080
    - name: S3_ENDPOINT
      value: "https://nrs.objectstore.gov.bc.ca:443"
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: s3-secrets
          key: ACCESS_KEY
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: s3-secrets
          key: BUCKET_NAME
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: s3-secrets
          key: SECRET_KEY

  resources:
    requests:
      cpu: 50m
      memory: 250Mi

  #-- the service for the component. for inter namespace communication, use the service name as the hostname.
  service:
    #-- the type of the service. it can be ClusterIP, NodePort, LoadBalancer, ExternalName. ClusterIP is the default and is recommended.
    type: ClusterIP
    port: 8000 # this is the service port, where it will be exposed internal to the namespace.
    targetPort: 8000 # this is container port where app listens on
  route:
    timeout: 300s
    targetPort: 8000 # match the service
  pdb:
    enabled: false # enable it in PRODUCTION for having pod disruption budget.
    minAvailable: 1 # the minimum number of pods that must be available during the disruption budget.


frontend:
  enabled: true
  deploymentStrategy: Recreate

  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    registry: ghcr.io 
    repository: bcgov/burn-severity-map/frontend
    # This sets the pull policy for images.
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  
  # env:
  #   - name: REACT_APP_BASE_URL
  #     value: "https://bs-app-burn-severity-map.apps.silver.devops.gov.bc.ca"

  resources:
    limits:
      cpu: 50m
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 250Mi

  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    enabled: true
    # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: ClusterIP
    # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
    port: 8080 # this is the service port, where it will be exposed internally to the namespace
    targetPort: 8080 # this is the container port where the app listens on
  route:
    timeout: 300s
    targetPort: 8080 # match the service
  domain: "apps.silver.devops.gov.bc.ca" # silver cluster
  # appName: "bs-app-burn-severity-map"
  baseUrl: "" # set per environment
  # add pdb??? 
  configMap:
    enabled: true

  # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    # make sure the pod/container runs as UID 1000 (the default for Caddy) and has write permissions
    # runAsUser: 1000 
    # runAsGroup: 1000
    # fsGroup: 1000


analysis:
  #-- enable or disable backend
  enabled: true
  #-- the deployment strategy, can be "Recreate" or "RollingUpdate"
  deploymentStrategy: Recreate
  #-- autoscaling for the component. it is optional and is an object.
  image:
    registry: ghcr.io
    repository: bcgov/burn-severity-map/analysis
    tag: latest # Or a specific tag
    pullPolicy: Always
  autoscaling:
    #-- enable or disable autoscaling.
    enabled: true
    #-- the minimum number of replicas.
    minReplicas: 3
    #-- the maximum number of replicas.
    maxReplicas: 7
    #-- the target cpu utilization percentage, is from request cpu and NOT LIMIT CPU.
    targetCPUUtilizationPercentage: 80
  configMap:
    enabled: false
  env:
    - name: PARQUET_PATH
      value: "burn-severity/bs.parquet"
    - name: TEMPDIR
      value: "/tmp"
    # Backend API
    - name: ANALYSIS_PORT
      value: 5000
    - name: BACKEND_PORT
      value: 8000
    - name: FRONTEND_PORT
      value: 8080
    - name: S3_ENDPOINT
      value: "https://nrs.objectstore.gov.bc.ca:443"
    - name: S3_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: s3-secrets
          key: ACCESS_KEY
    - name: S3_BUCKET_NAME
      valueFrom:
        secretKeyRef:
          name: s3-secrets
          key: BUCKET_NAME
    - name: S3_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: s3-secrets
          key: SECRET_KEY

  resources:
    requests:
      cpu: 250m
      memory: 500Mi

  #-- the service for the component. for inter namespace communication, use the service name as the hostname.
  service:
    #-- the type of the service. it can be ClusterIP, NodePort, LoadBalancer, ExternalName. ClusterIP is the default and is recommended.
    type: ClusterIP
    port: 5000 # this is the service port, where it will be exposed internal to the namespace.
    targetPort: 5000 # this is container port where app listens on
  route:
    timeout: 300s
    targetPort: 5000 # match the service
  pdb:
    enabled: false # enable it in PRODUCTION for having pod disruption budget.
    minAvailable: 1 # the minimum number of pods that must be available during the disruption budget.