apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-caddyfile
data:
  Caddyfile: |-
    {{- include (print $.Template.BasePath "/frontend/templates/Caddyfile") . | nindent 4 }}