{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "charts.labels" . | nindent 4 }}
spec:
{{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
{{- end }}
  selector:
    matchLabels:
{{- include "charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
{{- with .Values.podAnnotations }}
      annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
      labels:
{{- include "charts.labels" . | nindent 8 }}
{{- with .Values.podLabels }}
{{- toYaml . | nindent 8 }}
{{- end }}
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              add: ["NET_BIND_SERVICE"]
          image: "{{ .Values.frontend.image.registry }}/{{ .Values.frontend.image.repository }}:{{ default .Chart.AppVersion .Values.frontend.image.tag }}"
          imagePullPolicy: {{ default "Always" .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          env:
            - name: REACT_APP_BASE_URL
              value: {{ printf "https://%s.%s" .Values.frontend.appName .Values.frontend.domain | quote }}
  {{- with .Values.livenessProbe }}
          livenessProbe:
{{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.readinessProbe }}
          readinessProbe:
{{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.frontend.resources }}
          resources:
{{- toYaml . | nindent 12 }}
{{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          emptyDir: {}
        - name: caddyfile
          configMap:
            name: {{ include "charts.fullname" . }}-caddyfile
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}