name: Build and Publish
on:
  workflow_dispatch:

jobs:
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [frontend, backend/api, backend/bs-worker, analysis]
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.3.0
        with:
          keep_versions: 5
          package: ${{ matrix.package }}
          tag: latest
          tag_fallback: latest
          build_args: |
            REACT_APP_BASE_URL=https://bs-app-burn-severity-map.apps.silver.devops.gov.bc.ca
            REACT_APP_AUTH_CALLBACK_URL=https://bs-app-burn-severity-map.apps.silver.devops.gov.bc.ca/callback
