name: Deploy to prod

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The image tag (PR Number) from Test to promote to Prod"
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  vars:
    name: Set Variables
    outputs:
      tag: ${{ inputs.tag}}
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      - name: Echo Target Tag
        run: echo "Deploying tag ${{ inputs.tag }} to production"

  deploy-prod:
    name: Deploy (prod, tag=${{ needs.vars.outputs.tag }})
    needs: [vars]
    uses: ./.github/workflows/.deployer.yml
    secrets:
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      environment: prod
      params: >-
        --set global.secrets.persist=false
        --set-string frontend.baseUrl=https://burn-severity-map-prod-frontend.apps.silver.devops.gov.bc.ca
      tag: ${{ needs.vars.outputs.tag }}


  promote:
    name: Promote Images
    needs: [deploy-prod, vars]
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        # package: [migrations, backend, frontend]
        package: [analysis,backend,frontend]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ needs.vars.outputs.tag }}
          tags: prod