name: Sandbox Registry Check

# This runs immediately whenever you push to ANY branch
on: [push]

jobs:
  test-script:
    runs-on: ubuntu-24.04
    permissions:
      packages: read
    steps:
      - name: Check Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Hardcode the variables just for testing
          if docker manifest inspect ghcr.io/bcgov/analysis:v0.0.4 > /dev/null 2>&1; then
            echo "exists=true"
          else
            echo "exists=false"
          fi